### PR TITLE
Protocol chooser

### PR DESCRIPTION
**Pull request by seddarj**
This pull request adds a protocol chooser (HTTP and HTTPS) on the login page.
This way users don't have to input the protocol manually.

Solves #16 

Some screenshots below to see what it looks like.

screenshot_2017-09-03-15-55-23
screenshot_2017-09-03-15-49-58

### CODE REVIEW

**Comment by animalillo** [comment]
Please, gpg sign your commits. I like the idea a lot tho!

**Comment by seddarj** [comment]
After seeing the tests failed I realized I had to sign the commits. It should be fine now.
Thanks for your input!

**Comment by animalillo** [comment]
merged :3

**Comment by seddarj** [comment]
That was quick! Thanks ;-)

**Pull request merged**
