### PR TITLE
l10n: Correct name and ellipses

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Review by rakekniven — CHANGES_REQUESTED** [review]
@Valdnet Please remove blank before ellipsis at L37 .

**Review by rakekniven — APPROVED** [review]
Forget my last review. It is ok.

**Comment by Valdnet** [comment]
@rakekniven Thanks for approved 😉.

**Comment by Valdnet** [comment]
@rakekniven Do you have permission to merge it?

**Comment by rakekniven** [comment]
> Do you have permission to merge it?

checks fail.

Did you sign your commits?

**Comment by Valdnet** [comment]
@rakekniven I forgot :grin:. Now try it :wink:.

**Comment by rakekniven** [comment]
Two drone checks are not reporting back. Not sure if they are even startet to check :-/

**Comment by ChristophWurst** [comment]
Bildschirmfoto von 2021-03-18 16-34-42

**Comment by rakekniven** [comment]
@binsky08 Do you know who to contact regarding domain certs?

**Comment by Valdnet** [comment]
Is there any chance of merging? It has been hanging since February  :grimacing:.

**Comment by animalillo** [comment]
Regarding certs you can contact me, but i'm not sure what should be under the drone subdomain.
I will be merging this now :)

**Comment by rakekniven** [comment]
Great to see some action here.

**Pull request merged**
