### PR TITLE
Fix transifex

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Transifex is using values-es_419 for spanish "latin america", but this is not supported on android. This changes "values-es_419" to "values-es-rUS", which works.

### CODE REVIEW

**Comment by brantje** [comment]
@tobiasKaminsky Please do not merge without our review!

**Comment by tobiasKaminsky** [comment]
I did not. Maybe you mistaken the "merged" button from the referenced pull request? ;-)

**Comment by brantje** [comment]
Yea sorry, didn't finish my morning coffee.

**Comment by brantje** [comment]
Fixed with squashed merge due lack of signed commit.

**Pull request closed without merging**
