### PR TITLE
l10n: Correct spelling

### PR DESCRIPTION
**Pull request by Valdnet**
Unify the spelling in applications.

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]

**Comment by Valdnet** [comment]
@animalillo Please merge 😉.

**Comment by comradekingu** [comment]
@Valdnet You want to unify it the other way around to not introduce errors in translation.

**Comment by Valdnet** [comment]
@comradekingu I unify words across all Nextcloud apps to avoid spelling mismatches 😉.

**Comment by comradekingu** [comment]
@valdnet I get that, but you have picked the strictly less correct variant, and the one that introduces the most errors in translation. There is no way to mark something as terminology to ensure consistent translation on TX, and there isn't a consistency check from what I remember.

Just thought I'd chime in.

**Comment by animalillo** [comment]
Since both wordings are correct, and it does seem to spike some shenaningans, i think we will stick with E-mail on this app, thank you though!

**Comment by rakekniven** [comment]
Hello @animalillo. Valdnet spend many hours on github to align the words in many repos to improve the word base at Transifex. He created many PRs the last days and all of them had been merged.
Please see the global target.

**Comment by Valdnet** [comment]
@comradekingu We match the text strings from the main Nextcloud branch. In order for the application to look professional, it is necessary to standardize messages, warnings, descriptions, etc. This is the only way to achieve success.

@rakekniven Thanks for reopening the PR 👍.

@animalillo I am renewing my merge request 😉.

**Pull request merged**
